sudo: required
services:
  - docker

before_install:
  - docker build -t gracianohenrique/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true gracianohenrique/react-docker npm run test