name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_HOST: tcp://localhost:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t gracianohenrique/react-docker -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true gracianohenrique/react-docker npm run test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AWS CLI setup
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION_KEY }}

      - name: Set version label
        run: |
          export VERSION_LABEL="app-$(date +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)"
          echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV

      - name: Install EB CLI
        run: |
          pip install awsebcli

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Initialize EB CLI
        run: |
          eb init -p docker react-docker --region eu-north-1

      - name: Select Elastic Beanstalk environment
        run: |
          eb use Docker-react-env

      - name: Show platform version
        run: |
          eb platform show
          eb platform upgrade

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
