name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t gracianohenrique/react-docker -f Dockerfile.dev .
      - run: docker run -e CI=true gracianohenrique/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: Graciano1997/docker_react@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Docker-react
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-992382678646
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip